---
# tasks file for ansible-role-pacemaker

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  when: test_skip is undefined

- name: install pacemaker/corosync/pcs
  yum:
    name:
      - pacemaker
      - corosync
      - pcs

- name: install vipcheck module
  get_url:
    url: https://dotsrc.dl.osdn.net/osdn/linux-ha/45456/VIPcheck
    dest: /usr/lib/ocf/resource.d/heartbeat/VIPcheck
    mode: 0755

- name: start pcsd service
  service:
    name: pcsd
    state: started
    enabled: yes

- name: set password (hacluster user)
  user:
    name: hacluster
    password: "{{ pacemaker_cluster_auth_password | password_hash('sha512', pacemaker_cluster_auth_password) }}"

- name: auth cluster nodes
  command: "pcs cluster auth -u hacluster -p {{ pacemaker_cluster_auth_password }} {{ ansible_play_hosts | join(' ') }} --force"
  args:
    creates: /etc/corosync/corosync.conf

- name: setup cluster
  command: "pcs cluster setup --name {{ pacemaker_cluster_name }} {{ ansible_play_hosts | zip(pacemaker_cluster_hosts) | flatten | join(' ') | regex_replace('\\s\\d{1,3}(\\.\\d{1,3}){3}','') if pacemaker_cluster_hosts != None else ansible_play_hosts | join(' ') }} --force"
  args:
    creates: /etc/corosync/corosync.conf

- name: check cluster status
  command: pcs status
  register: pcs_status
  failed_when: pcs_status.rc not in [0, 1]
  changed_when: no
  check_mode: no

- name: start cluster
  command: pcs cluster start --all
  when: pcs_status.rc != 0
