---
# tasks file for ansible-role-pacemaker

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  when: test_skip is undefined

- name: install pacemaker/corosync/pcs
  yum:
    name:
      - pacemaker
      - corosync
      - pcs

- name: start pcsd service
  service:
    name: pcsd
    state: started
    enabled: yes

- name: set password (hacluster user)
  user:
    name: hacluster
    password: "{{ pacemaker_cluster_auth_password | password_hash('sha512', pacemaker_cluster_auth_password) }}"

- name: detect corosync.conf
  stat:
    path: /etc/corosync/corosync.conf
  register: corosync_conf

- name: auth cluster nodes
  command: "pcs cluster auth -u hacluster -p {{ pacemaker_cluster_auth_password }} {{ pacemaker_cluster_hosts | join(' ') | replace(',',' ') }}"
  when: not corosync_conf.stat.exists

- name: setup cluster
  command: "pcs cluster setup --name {{ pacemaker_cluster_name }} {{ pacemaker_cluster_hosts | join(' ') }}"
  args:
    creates: /etc/corosync/corosync.conf

- name: check cluster status
  command: pcs status
  register: pcs_status
  failed_when: pcs_status.rc not in [0, 1]
  changed_when: no
  check_mode: no

- name: start cluster
  command: pcs cluster start --all
  when: pcs_status.rc != 0
